export default {
  TOKEN_KEY: '@KUSSOMA:TOKEN',
  ROLE_KEY: '@KUSSOMA:ROLE',
  USER_KEY: '@KUSSOMA:USER',
  PUSH_TOKEN_KEY: '@KUSSOMA:PUSH_TOKEN',
  GOOGLE_API_KEY: 'AIzaSyAnSyNvvVPZcykP0ki0BmJOBKcWqyThY54',
};
